name: Quarkus Codestart CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags: [ v* ]
jobs:
  publish-tags-starting-with-v:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: github-mcarlett-rest-camel
          settings-path: ${{ github.workspace }}/config
      - name: 'Deploy artifact'
        run: ./mvnw deploy -B -s ${{ github.workspace }}/config/settings.xml
