name: Create Maven Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
        default: '0.0.0'
      devel-version:
        description: 'Development version'
        required: true
        default: '0.0.0-SNAPSHOT'
      release-branch:
        description: 'Release branch'
        required: true
        default: 'master'    
      devel-branch:
        description: 'Development branch'
        required: true
        default: 'develop'

jobs:
  perform-release:
    runs-on: ubuntu-latest
    name: Perform Maven release
    steps:
    - id: checkout
      uses: actions/checkout@v2
    - id: perform
      uses: mcarlett/release-explicit-version-action@v0.19
      with:
        release-version: ${{ github.event.inputs.release-version }}
        devel-version: ${{ github.event.inputs.devel-version }}
        devel-branch: ${{ github.event.inputs.devel-branch }}
        release-branch: ${{ github.event.inputs.release-branch }}
    - id: show-tag
      run: "echo generated release: ${{ steps.perform.outputs.generated-tag }}"
      shell: bash
